export const PATH = {
  home: '/',
  fraijour: '/fraijour',
  lines: {
    heartLeaf: 'heartLeaf',
    originalArtemisia: 'originalArtemisia',
    originalHerbWormwood: 'originalHerbWormwood',
    yuzuHoney: 'yuzuHoney',
    retinCollagen3dCode: 'retinCollagen3dCode',
    proMoisture: 'proMoisture',
    biome5lacto: 'biome5lacto',
  },
  retinCollagen3dCodeLine: {
    product1: 'product1',
    product2: 'product2',
    product3: 'product3',
    product4: 'product4',
    product5: 'product5',
  },
  yuzuHoneyLine: {
    product1: 'product1',
    product2: 'product2',
    product3: 'product3',
    product4: 'product4',
    product5: 'product5',
    product6: 'product6',
  },
  originalHerbWormwoodLine: {
    product1: 'product1',
    product2: 'product2',
    product3: 'product3',
    product4: 'product4',
    product5: 'product5',
    product6: 'product6',
    product7: 'product7',
    product8: 'product8',
    product9: 'product9',
  },
  biome5lactoLine: {
    product1: 'product1',
    product2: 'product2',
    product3: 'product3',
    product4: 'product4',
  },
  proMoistureLine: {
    product1: 'product1',
    product2: 'product2',
    product3: 'product3',
    product4: 'product4',
  },
  heartLeafLine: {
    product1: 'product1',
    product2: 'product2',
    product3: 'product3',
    product4: 'product4',
  },
};
